spring:
  application:
    name: costrip-backend

  datasource:
    url: jdbc:mariadb://${DB_HOST:25.2.109.64}:${DB_PORT:3306}/${DB_DATABASE:4team_db}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:user}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MariaDBDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true


server:
  port: 8080

app:
  upload-dir: ${APP_UPLOAD_DIR:uploads}

jwt:
  secret: ${JWT_SECRET:5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437}
  expiration: ${JWT_EXPIRATION:3600}

anthropic:
  api:
    key: ${ANTHROPIC_API_KEY}