CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMP
);

CREATE TABLE trips (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    country VARCHAR(100) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    created_at TIMESTAMP,
    CONSTRAINT fk_trip_user
        FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE journal_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL,
    record_date DATE NOT NULL,
    memo VARCHAR(1000),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_journal_entry_trip
        FOREIGN KEY (trip_id) REFERENCES trips(id)
);

CREATE TABLE attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL,
    journal_entry_id BIGINT,
    file_name VARCHAR(255),
    file_path VARCHAR(500),
    file_type VARCHAR(50),
    created_at TIMESTAMP,
    CONSTRAINT fk_attachment_trip
        FOREIGN KEY (trip_id) REFERENCES trips(id),
    CONSTRAINT fk_attachment_journal_entry
        FOREIGN KEY (journal_entry_id) REFERENCES journal_entries(id)
);
